version: "3"

services:
  mysql8:
    image: "mysql:8.4.0"
    container_name: "mysql8"
    environment:
      - "MYSQL_ROOT_PASSWORD=root" # 设置root用户密码
      - "TZ=Asia/Shanghai" # 设置时区
    volumes: # 文件映射
      - "./data/conf:/etc/mysql/conf.d"
      - "./data/mysql:/var/lib/mysql"
      - "./data/logs:/var/log/mysql"
    ports:
      - "13306:3306" # 端口映射
    privileged: true
    command: ["--character-set-server=utf8mb4","--collation-server=utf8mb4_unicode_ci"]