version: "3"

services:
  mongodb6:
    #    image: "mongo:6.0.15"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mongodb6-1
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: moment
      MONGO_INITDB_ROOT_PASSWORD: moment
    volumes:
      - ./mongo-keyfile:/opt/keyfile/mongo-keyfile:ro
      - ./data/db1:/data/db
    command: mongod --replSet rs0 --auth --keyFile /opt/keyfile/mongo-keyfile
    networks:
      - mongo-network

  mongodb6-2:
    #    image: "mongo:6.0.15"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mongodb6-2
    depends_on:
      - mongodb6-1
    environment:
      MONGO_INITDB_ROOT_USERNAME: moment
      MONGO_INITDB_ROOT_PASSWORD: moment
    volumes:
      - ./mongo-keyfile:/opt/keyfile/mongo-keyfile:ro
      - ./data/db2:/data/db
    command: mongod --replSet rs0 --auth --keyFile /opt/keyfile/mongo-keyfile
    networks:
      - mongo-network

  mongodb6-3:
    #    image: "mongo:6.0.15"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mongodb6-3
    depends_on:
      - mongodb6-1
    environment:
      MONGO_INITDB_ROOT_USERNAME: moment
      MONGO_INITDB_ROOT_PASSWORD: moment
    volumes:
      - ./mongo-keyfile:/opt/keyfile/mongo-keyfile:ro
      - ./data/db3:/data/db

    command: mongod --replSet rs0 --auth --keyFile /opt/keyfile/mongo-keyfile --oplogSize 128
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge