version: '3'

services:
  mongodb4-1:
    image: "mongo:4.4.10"
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: mongodb4-1
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: moment
      MONGO_INITDB_ROOT_PASSWORD: moment
    volumes:
      # - ./mongo-keyfile:/opt/keyfile/mongo-keyfile:ro
      - ./data/db1:/data/db
    # command: mongod --replSet rs0 --auth --keyFile /opt/keyfile/mongo-keyfile
    command: mongod --replSet rs0
    networks:
      - mongo-network

  mongodb4-2:
    image: "mongo:4.4.10"
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: mongodb4-2
    depends_on:
      - mongodb4-1
    environment:
      MONGO_INITDB_ROOT_USERNAME: moment
      MONGO_INITDB_ROOT_PASSWORD: moment
    volumes:
      # - ./mongo-keyfile:/opt/keyfile/mongo-keyfile:ro
      - ./data/db2:/data/db
    # command: mongod --replSet rs0 --auth --keyFile /opt/keyfile/mongo-keyfile
    command: mongod --replSet rs0
    networks:
      - mongo-network

  mongodb4-3:
    image: "mongo:4.4.10"
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: mongodb4-3
    depends_on:
      - mongodb4-1
    environment:
      MONGO_INITDB_ROOT_USERNAME: moment
      MONGO_INITDB_ROOT_PASSWORD: moment
    volumes:
      # - ./mongo-keyfile:/opt/keyfile/mongo-keyfile:ro
      - ./data/db3:/data/db

    # command: mongod --replSet rs0 --auth --keyFile /opt/keyfile/mongo-keyfile --oplogSize 128
    command: mongod --replSet rs0 --oplogSize 128
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge