version: '3.8'

services:
  mongo6:
    image: mongodb/mongodb-community-server:6.0.15-ubi8
    container_name: mongo6
    environment:
      - TZ=Asia/Shanghai
      - MONGODB_INITDB_ROOT_USERNAME=zeng
      - MONGODB_INITDB_ROOT_PASSWORD=zeng
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    networks:
      - mongo_network

networks:
  mongo_network:
    driver: bridge